server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: duc432003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: leanhduc04032003@gmail.com
    password: vdpyfauswmukpfxg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


